use clap::Parser;
use ebonify::cli;
use ebonify::cli::Commands;
use ebonify::data_formatting::*;

fn main() {
    let cli = crate::cli::Cli::parse();
    match &cli.command {
        Some(Commands::Convert(argmts)) => {
            match (&argmts.from_type, &argmts.dest_type) {
                (cli::SourceType::File, cli::SourceType::JSON) => {
                    let data = FileData::new(&argmts.value);
                    match data.get_json() {
                        Ok(v) => if argmts.pretty {
                            print!("{:#}", v)
                        } else {
                            print!("{}", v)
                        },
                        Err(e) => println!("{}", e.to_string()),
                    }
                },
                _ => println!("Other methods not implemented")
            }
        },
        Some(Commands::Match(_)) => println!("Trying to check if a token is generated by a formal language"),
        None => println!("No command selected"),
    }
}