// mod ebnf_syntax;
// mod error;
// mod parsing;
// mod ast;
// mod structure;
// mod utils;
mod cli;

use cli::Commands;
use clap::Parser;
// use structure::EbnfTree;

fn main() {
    let cli = crate::cli::Cli::parse();
    match &cli.command {
        Some(Commands::Convert(_)) => println!("Trying to convert value"),
        Some(Commands::Match(_)) => println!("Trying to check if a token is generated by a forma language"),
        None => println!("No command selected"),
    }
}